FAT-899 Added identifiers to elements to use in cypress tests
folio-org/stripes-smart-components pull request #1079
Opened 2021-06-22 08:09 UTC by BogdanDenis

## Description
Added ids to some elements to be able to find them in Cypress tests

## Related PRs
https://github.com/folio-org/stripes-testing/pull/111

2021-06-22 08:40 UTC, mariiaschv commented on lib/Notes/components/NotesAccordion/components/NotesAssigningModal/NotesAssigningModal.js
> +    )),
You can remove redundant parentheses to get rid of a code smell.
```suggestion
    [columnNames.TITLE]: (note) => (
      <span className="note-title">{note.title}</span>
    ),
```

2021-06-22 14:02 UTC, mariiaschv approved these changes

2021-06-22 14:42 UTC, zburke commented on lib/Notes/components/NotesAccordion/NotesAccordion.js
> +              id="note-assign"
Since you established the `...-button` convention above, it would be great to follow through with it. Consistency makes test-writing so much easier.

2021-06-22 14:56 UTC, zburke requested changes
Please follow the `...-button` convention for all buttons.

2021-06-23 11:20 UTC, zburke requested changes
Almost there; just a few more button-ids to update.

2021-06-23 11:20 UTC, zburke commented on lib/Notes/components/NotesAccordion/NotesAccordion.js
> +            id="note-create"
`note-create-button`

2021-06-23 11:20 UTC, zburke commented on lib/Notes/components/NotesAccordion/components/NotesAssigningModal/NotesAssigningModal.js
> +          id="notes-modal-cancel"
`notes-modal-cancel-button`

2021-06-24 10:33 UTC, Vladyslav-Velytskyi approved these changes

2021-06-24 13:14 UTC, merged