STSMACOM-520: Pop-up note: Display Notes title
folio-org/stripes-smart-components pull request #1083
Opened 2021-06-23 15:27 UTC by mariiaschv

## Description
Always display Notes title and hide details if not present.

Issue: [STSMACOM-520](https://issues.folio.org/browse/STSMACOM-520)

2021-06-23 16:00 UTC, Vladyslav-Velytskyi requested changes
Please, update CHANGELOG.md

2021-06-23 16:12 UTC, Vladyslav-Velytskyi approved these changes

2021-06-24 07:52 UTC, Vladyslav-Velytskyi commented on lib/Notes/NotePopupModal/NotePopupModal.js
> +      { popupContentHTML.__html && detailsContent }
Pleasem keep code in one style
```suggestion
      {titleContent}
      {popupContentHTML.__html && detailsContent}
```

2021-06-29 10:19 UTC, BogdanDenis requested changes

2021-06-29 10:19 UTC, BogdanDenis commented on lib/Notes/NotePopupModal/NotePopupModal.js
> +        data-test-note-popup-modal-content
Please add class `ql-editor`. It makes sure that details are displayed in the same way as in create or edit page

2021-06-29 11:05 UTC, BogdanDenis approved these changes

2021-06-29 12:16 UTC, merged