STSMACOM-697: Add the ability to add a new parameter to the URL and synchronize it with the value of the search field.
folio-org/stripes-smart-components pull request #1276
Opened 2022-08-05 18:39 UTC by Dmytro-Melnyshyn

2022-08-09 15:50 UTC, BogdanDenis requested changes

2022-08-09 16:55 UTC, Dmytro-Melnyshyn commented on lib/SearchAndSort/ConnectedSource/StripesConnectedSource.js
> +  fetchByQuery(browsePoint) {
Thanks for noticing, I've changed the name.

2022-08-10 07:47 UTC, Dmytro-Melnyshyn commented
@mkuklis please take a look

2022-08-10 07:48 UTC, BogdanDenis approved these changes

2022-08-10 13:37 UTC, mkuklis approved these changes
@Dmytro-Melnyshyn this looks much cleaner than relying on `regExpForQuery`. Nice work! Thank you for documenting it too.

2022-08-10 13:40 UTC, merged